# Generated by Django 3.2.4 on 2021-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_auto_20210622_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комменты',
                'verbose_name_plural': 'Комент',
            },
        ),
    ]
